# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from wallet import wallet_pb2 as wallet_dot_wallet__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in wallet/wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createWallet = channel.unary_unary(
                '/wallet.Wallets/createWallet',
                request_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                _registered_method=True)
        self.updateWallet = channel.unary_unary(
                '/wallet.Wallets/updateWallet',
                request_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                _registered_method=True)
        self.deleteWallet = channel.unary_unary(
                '/wallet.Wallets/deleteWallet',
                request_serializer=wallet_dot_wallet__pb2.WalletID.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                _registered_method=True)
        self.getWallet = channel.unary_unary(
                '/wallet.Wallets/getWallet',
                request_serializer=wallet_dot_wallet__pb2.WalletID.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                _registered_method=True)
        self.getUsersWallets = channel.unary_unary(
                '/wallet.Wallets/getUsersWallets',
                request_serializer=wallet_dot_wallet__pb2.UserID.SerializeToString,
                response_deserializer=wallet_dot_wallet__pb2.WalletList.FromString,
                _registered_method=True)


class WalletsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUsersWallets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.createWallet,
                    request_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                    response_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
            ),
            'updateWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.updateWallet,
                    request_deserializer=wallet_dot_wallet__pb2.Wallet.FromString,
                    response_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
            ),
            'deleteWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteWallet,
                    request_deserializer=wallet_dot_wallet__pb2.WalletID.FromString,
                    response_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
            ),
            'getWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.getWallet,
                    request_deserializer=wallet_dot_wallet__pb2.WalletID.FromString,
                    response_serializer=wallet_dot_wallet__pb2.Wallet.SerializeToString,
            ),
            'getUsersWallets': grpc.unary_unary_rpc_method_handler(
                    servicer.getUsersWallets,
                    request_deserializer=wallet_dot_wallet__pb2.UserID.FromString,
                    response_serializer=wallet_dot_wallet__pb2.WalletList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.Wallets', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.Wallets', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Wallets(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/createWallet',
            wallet_dot_wallet__pb2.Wallet.SerializeToString,
            wallet_dot_wallet__pb2.Wallet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/updateWallet',
            wallet_dot_wallet__pb2.Wallet.SerializeToString,
            wallet_dot_wallet__pb2.Wallet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/deleteWallet',
            wallet_dot_wallet__pb2.WalletID.SerializeToString,
            wallet_dot_wallet__pb2.Wallet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/getWallet',
            wallet_dot_wallet__pb2.WalletID.SerializeToString,
            wallet_dot_wallet__pb2.Wallet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getUsersWallets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.Wallets/getUsersWallets',
            wallet_dot_wallet__pb2.UserID.SerializeToString,
            wallet_dot_wallet__pb2.WalletList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
